version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    container_name: timeslotAPI
    volumes:
      - .:/timeslotAPI
    ports:
      - "8081:8001"